# Generated by Django 4.2.8 on 2023-12-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClickEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_name", models.CharField(max_length=1000)),
                ("page_section_name", models.CharField(max_length=1000)),
                ("clicked_element_name", models.CharField(max_length=1000)),
                ("clicked_element_type", models.CharField(max_length=1000)),
                ("time_spent_on_page", models.CharField(max_length=1000)),
            ],
            options={
                "db_table": "click_events",
            },
        ),
    ]
